# POST http://localhost:4000/app/signup
# Content-Type: application/json

# {
#     "fullName":"Joseph",
#     "username":"joey",
#     "email":"joey@email.com",
#     "password":"josejo"
# }

POST http://localhost:400/app/login
Content-Type: application/json

{
    "username":"joey",
    "password":"josejo"
}